// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbp5hcVxVlVWi_AbcyvmVmn_ClL7aZYF0',
    appId: '1:646857113286:web:your-web-app-id',
    messagingSenderId: '646857113286',
    projectId: 'inventorymanager-bc334',
    authDomain: 'inventorymanager-bc334.firebaseapp.com',
    storageBucket: 'inventorymanager-bc334.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbp5hcVxVlVWi_AbcyvmVmn_ClL7aZYF0',
    appId: '1:646857113286:android:02264deccbc3199dd521c7',
    messagingSenderId: '646857113286',
    projectId: 'inventorymanager-bc334',
    storageBucket: 'inventorymanager-bc334.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbp5hcVxVlVWi_AbcyvmVmn_ClL7aZYF0',
    appId: '1:646857113286:ios:your-ios-app-id',
    messagingSenderId: '646857113286',
    projectId: 'inventorymanager-bc334',
    storageBucket: 'inventorymanager-bc334.firebasestorage.app',
    iosBundleId: 'com.example.inventorymanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbp5hcVxVlVWi_AbcyvmVmn_ClL7aZYF0',
    appId: '1:646857113286:ios:your-macos-app-id',
    messagingSenderId: '646857113286',
    projectId: 'inventorymanager-bc334',
    storageBucket: 'inventorymanager-bc334.firebasestorage.app',
    iosBundleId: 'com.example.inventorymanager',
  );
}
